import argparse
import json
import re
from pathlib import Path

import cv2
import numpy as np


# ============================================================
# NATURAL SORTING
# ============================================================

def natural_sort_key(path):
    """
    Allows:

        pair_1
        pair_2
        pair_10

    instead of:

        pair_1
        pair_10
        pair_2
    """

    return [
        int(text) if text.isdigit()
        else text.lower()

        for text in re.split(
            r"(\d+)",
            path.name,
        )
    ]


# ============================================================
# FIND MATCH FILES
# ============================================================

def find_match_files(matches_dir):
    """
    Finds the NPZ files generated by feature_matching.py.
    """

    matches_dir = Path(
        matches_dir
    )

    if not matches_dir.exists():

        raise RuntimeError(
            "\nMatch directory does not exist:\n"
            f"{matches_dir}\n"
        )

    files = list(
        matches_dir.glob(
            "pair_*_matches.npz"
        )
    )

    return sorted(
        files,
        key=natural_sort_key,
    )


# ============================================================
# LOAD MATCH FILE
# ============================================================

def load_match_file(match_file):
    """
    Loads matched point correspondences.

    points_a[i] corresponds to points_b[i].
    """

    data = np.load(
        match_file
    )

    return {
        "pair_id": int(
            data["pair_id"]
        ),

        "image_a": str(
            data["image_a"]
        ),

        "image_b": str(
            data["image_b"]
        ),

        "points_a": (
            data["points_a"]
            .astype(np.float32)
        ),

        "points_b": (
            data["points_b"]
            .astype(np.float32)
        ),

        "distances": (
            data["distances"]
            .astype(np.float32)
        ),
    }


# ============================================================
# PROJECT POINTS USING HOMOGRAPHY
# ============================================================

def project_points(
    points,
    homography,
):
    """
    Applies the homography to 2D points.

    For this pipeline:

        point_b ~ H_a_to_b * point_a
    """

    points = np.asarray(
        points,
        dtype=np.float32,
    )

    points = points.reshape(
        -1,
        1,
        2,
    )

    projected = cv2.perspectiveTransform(
        points,
        homography,
    )

    return projected.reshape(
        -1,
        2,
    )


# ============================================================
# REPROJECTION ERROR
# ============================================================

def calculate_reprojection_errors(
    homography,
    points_a,
    points_b,
):
    """
    Projects points from image A into image B
    and measures the Euclidean pixel error.

        p_b_estimated = H * p_a

    error =
        || p_b_actual - p_b_estimated ||
    """

    projected = project_points(
        points_a,
        homography,
    )

    errors = np.linalg.norm(
        projected - points_b,
        axis=1,
    )

    return errors


# ============================================================
# HOMOGRAPHY WITH RANSAC
# ============================================================

def estimate_homography_ransac(
    points_a,
    points_b,
    reprojection_threshold=3.0,
    confidence=0.995,
    max_iterations=5000,
):
    """
    Estimates a planar homography using RANSAC.

    Direction:

        IMAGE A -> IMAGE B

    so:

        p_b ~ H_a_to_b * p_a

    RANSAC repeatedly selects minimal subsets,
    estimates candidate homographies and checks
    which correspondences agree geometrically.
    """

    number_matches = len(
        points_a
    )

    if number_matches < 4:

        raise RuntimeError(
            "A homography requires at least "
            "4 point correspondences."
        )

    # Make RANSAC behavior reproducible.
    cv2.setRNGSeed(42)

    homography, mask = cv2.findHomography(
        points_a,
        points_b,
        cv2.RANSAC,
        reprojection_threshold,
        None,
        max_iterations,
        confidence,
    )

    if (
        homography is None
        or mask is None
    ):

        raise RuntimeError(
            "RANSAC could not estimate "
            "a valid homography."
        )

    homography = homography.astype(
        np.float64
    )

    # --------------------------------------------------------
    # Normalize projective scale
    # --------------------------------------------------------

    if abs(
        homography[2, 2]
    ) > 1e-12:

        homography /= (
            homography[2, 2]
        )

    # --------------------------------------------------------
    # Make sure matrix contains valid numbers
    # --------------------------------------------------------

    if not np.all(
        np.isfinite(
            homography
        )
    ):

        raise RuntimeError(
            "Homography contains invalid values."
        )

    inlier_mask = (
        mask
        .reshape(-1)
        .astype(bool)
    )

    number_inliers = int(
        np.sum(
            inlier_mask
        )
    )

    if number_inliers < 4:

        raise RuntimeError(
            "RANSAC found fewer than "
            "4 geometrically consistent matches."
        )

    # --------------------------------------------------------
    # Calculate reprojection errors
    # --------------------------------------------------------

    errors = (
        calculate_reprojection_errors(
            homography,
            points_a,
            points_b,
        )
    )

    inlier_errors = (
        errors[
            inlier_mask
        ]
    )

    mean_error = float(
        np.mean(
            inlier_errors
        )
    )

    rms_error = float(
        np.sqrt(
            np.mean(
                inlier_errors ** 2
            )
        )
    )

    median_error = float(
        np.median(
            inlier_errors
        )
    )

    inlier_ratio = (
        number_inliers
        / number_matches
    )

    # --------------------------------------------------------
    # Calculate inverse transformation
    #
    # H_a_to_b:
    #     image A -> image B
    #
    # H_b_to_a:
    #     image B -> image A
    # --------------------------------------------------------

    determinant = np.linalg.det(
        homography
    )

    if abs(determinant) < 1e-12:

        raise RuntimeError(
            "Homography is singular and "
            "cannot be inverted."
        )

    inverse_homography = (
        np.linalg.inv(
            homography
        )
    )

    inverse_homography /= (
        inverse_homography[2, 2]
    )

    return {
        "homography_a_to_b": (
            homography
        ),

        "homography_b_to_a": (
            inverse_homography
        ),

        "inlier_mask": (
            inlier_mask
        ),

        "number_matches": (
            number_matches
        ),

        "number_inliers": (
            number_inliers
        ),

        "inlier_ratio": (
            inlier_ratio
        ),

        "mean_error": (
            mean_error
        ),

        "rms_error": (
            rms_error
        ),

        "median_error": (
            median_error
        ),

        "all_errors": (
            errors
        ),
    }


# ============================================================
# SAVE HOMOGRAPHY
# ============================================================

def save_homography(
    output_file,
    pair_data,
    result,
    reprojection_threshold,
    confidence,
    max_iterations,
):
    """
    Saves the transformation and RANSAC results.
    """

    output_file = Path(
        output_file
    )

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    points_a = (
        pair_data[
            "points_a"
        ]
    )

    points_b = (
        pair_data[
            "points_b"
        ]
    )

    inlier_mask = (
        result[
            "inlier_mask"
        ]
    )

    np.savez_compressed(
        output_file,

        pair_id=np.array(
            pair_data[
                "pair_id"
            ]
        ),

        image_a=np.array(
            pair_data[
                "image_a"
            ]
        ),

        image_b=np.array(
            pair_data[
                "image_b"
            ]
        ),

        # ----------------------------------------------------
        # Transformations
        # ----------------------------------------------------

        homography_a_to_b=(
            result[
                "homography_a_to_b"
            ]
        ),

        homography_b_to_a=(
            result[
                "homography_b_to_a"
            ]
        ),

        # ----------------------------------------------------
        # All matched points
        # ----------------------------------------------------

        points_a=points_a,

        points_b=points_b,

        # ----------------------------------------------------
        # RANSAC result
        # ----------------------------------------------------

        inlier_mask=(
            inlier_mask.astype(
                np.uint8
            )
        ),

        inlier_points_a=(
            points_a[
                inlier_mask
            ]
        ),

        inlier_points_b=(
            points_b[
                inlier_mask
            ]
        ),

        number_matches=np.array(
            result[
                "number_matches"
            ]
        ),

        number_inliers=np.array(
            result[
                "number_inliers"
            ]
        ),

        inlier_ratio=np.array(
            result[
                "inlier_ratio"
            ]
        ),

        mean_reprojection_error=np.array(
            result[
                "mean_error"
            ]
        ),

        rms_reprojection_error=np.array(
            result[
                "rms_error"
            ]
        ),

        median_reprojection_error=np.array(
            result[
                "median_error"
            ]
        ),

        reprojection_errors=(
            result[
                "all_errors"
            ]
        ),

        # ----------------------------------------------------
        # RANSAC configuration
        # ----------------------------------------------------

        ransac_threshold=np.array(
            reprojection_threshold
        ),

        ransac_confidence=np.array(
            confidence
        ),

        ransac_max_iterations=np.array(
            max_iterations
        ),
    )


# ============================================================
# LOAD HOMOGRAPHY
# ============================================================

def load_homography(
    homography_file,
):
    """
    Loads a saved pairwise homography.

    This will be used later by warping.py.
    """

    data = np.load(
        homography_file
    )

    return {
        "pair_id": int(
            data["pair_id"]
        ),

        "image_a": str(
            data["image_a"]
        ),

        "image_b": str(
            data["image_b"]
        ),

        "homography_a_to_b": (
            data[
                "homography_a_to_b"
            ]
        ),

        "homography_b_to_a": (
            data[
                "homography_b_to_a"
            ]
        ),

        "number_matches": int(
            data[
                "number_matches"
            ]
        ),

        "number_inliers": int(
            data[
                "number_inliers"
            ]
        ),

        "inlier_ratio": float(
            data[
                "inlier_ratio"
            ]
        ),

        "rms_error": float(
            data[
                "rms_reprojection_error"
            ]
        ),
    }


# ============================================================
# DEBUG VISUALIZATION
# ============================================================

def create_ransac_visualization(
    image_a,
    image_b,
    points_a,
    points_b,
    inlier_mask,
    max_drawn=200,
):
    """
    Creates a side-by-side visualization.

    Green:
        RANSAC inlier

    Red:
        rejected match / outlier
    """

    if (
        image_a is None
        or image_b is None
    ):

        raise ValueError(
            "Images cannot be None."
        )

    # --------------------------------------------------------
    # Convert grayscale if necessary
    # --------------------------------------------------------

    if len(
        image_a.shape
    ) == 2:

        image_a = cv2.cvtColor(
            image_a,
            cv2.COLOR_GRAY2BGR,
        )

    if len(
        image_b.shape
    ) == 2:

        image_b = cv2.cvtColor(
            image_b,
            cv2.COLOR_GRAY2BGR,
        )

    height_a, width_a = (
        image_a.shape[:2]
    )

    height_b, width_b = (
        image_b.shape[:2]
    )

    canvas_height = max(
        height_a,
        height_b,
    )

    canvas_width = (
        width_a
        + width_b
    )

    canvas = np.zeros(
        (
            canvas_height,
            canvas_width,
            3,
        ),
        dtype=np.uint8,
    )

    canvas[
        0:height_a,
        0:width_a,
    ] = image_a

    canvas[
        0:height_b,
        width_a:width_a + width_b,
    ] = image_b

    # --------------------------------------------------------
    # Limit number drawn so debug image remains readable
    # --------------------------------------------------------

    number_points = len(
        points_a
    )

    number_drawn = min(
        number_points,
        max_drawn,
    )

    for index in range(
        number_drawn
    ):

        point_a = points_a[
            index
        ]

        point_b = points_b[
            index
        ]

        x_a = int(
            round(
                point_a[0]
            )
        )

        y_a = int(
            round(
                point_a[1]
            )
        )

        x_b = int(
            round(
                point_b[0]
            )
        ) + width_a

        y_b = int(
            round(
                point_b[1]
            )
        )

        if inlier_mask[index]:

            # Green = RANSAC inlier
            color = (
                0,
                255,
                0,
            )

        else:

            # Red = rejected match
            color = (
                0,
                0,
                255,
            )

        cv2.circle(
            canvas,
            (
                x_a,
                y_a,
            ),
            4,
            color,
            -1,
        )

        cv2.circle(
            canvas,
            (
                x_b,
                y_b,
            ),
            4,
            color,
            -1,
        )

        cv2.line(
            canvas,
            (
                x_a,
                y_a,
            ),
            (
                x_b,
                y_b,
            ),
            color,
            1,
            cv2.LINE_AA,
        )

    return canvas


# ============================================================
# FIND IMAGE
# ============================================================

def find_image(
    image_dir,
    image_name,
):
    """
    Finds the corresponding undistorted panorama image.
    """

    image_path = (
        Path(image_dir)
        / image_name
    )

    if not image_path.exists():

        raise RuntimeError(
            "\nImage not found:\n"
            f"{image_path}\n"
        )

    return image_path


# ============================================================
# PROCESS ALL PAIRS
# ============================================================

def estimate_all_homographies(
    matches_dir,
    image_dir,
    output_dir,
    reprojection_threshold=3.0,
    confidence=0.995,
    max_iterations=5000,
):
    """
    Estimates a RANSAC homography for every adjacent
    panorama pair.
    """

    matches_dir = Path(
        matches_dir
    )

    image_dir = Path(
        image_dir
    )

    output_dir = Path(
        output_dir
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    debug_dir = (
        output_dir.parent
        / "debug"
        / "homographies"
    )

    debug_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    match_files = (
        find_match_files(
            matches_dir
        )
    )

    if not match_files:

        raise RuntimeError(
            "\nNo feature match files found in:\n"
            f"{matches_dir}\n"
        )

    print()
    print("========================================")
    print(" HOMOGRAPHY ESTIMATION WITH RANSAC")
    print("========================================")
    print()

    print(
        f"Match files: "
        f"{len(match_files)}"
    )

    print(
        f"RANSAC reprojection threshold: "
        f"{reprojection_threshold:.2f} px"
    )

    print(
        f"RANSAC confidence: "
        f"{confidence}"
    )

    print(
        f"Maximum RANSAC iterations: "
        f"{max_iterations}"
    )

    print()

    results = []

    # ========================================================
    # PROCESS EACH IMAGE PAIR
    # ========================================================

    for index, match_file in enumerate(
        match_files,
        start=1,
    ):

        pair = load_match_file(
            match_file
        )

        print(
            f"[{index}/{len(match_files)}] "
            f"{pair['image_a']} "
            f"-> "
            f"{pair['image_b']}"
        )

        points_a = (
            pair[
                "points_a"
            ]
        )

        points_b = (
            pair[
                "points_b"
            ]
        )

        number_matches = len(
            points_a
        )

        print(
            f"  Feature matches: "
            f"{number_matches}"
        )

        # ----------------------------------------------------
        # Need minimum four matches
        # ----------------------------------------------------

        if number_matches < 4:

            print(
                "  ERROR: fewer than 4 matches."
            )

            print(
                "  Homography skipped."
            )

            print()

            results.append(
                {
                    "pair_id": (
                        pair[
                            "pair_id"
                        ]
                    ),

                    "success": False,

                    "reason": (
                        "fewer than 4 matches"
                    ),
                }
            )

            continue

        try:

            result = (
                estimate_homography_ransac(
                    points_a,
                    points_b,
                    reprojection_threshold=(
                        reprojection_threshold
                    ),
                    confidence=(
                        confidence
                    ),
                    max_iterations=(
                        max_iterations
                    ),
                )
            )

        except RuntimeError as error:

            print(
                f"  ERROR: {error}"
            )

            print()

            results.append(
                {
                    "pair_id": (
                        pair[
                            "pair_id"
                        ]
                    ),

                    "success": False,

                    "reason": str(
                        error
                    ),
                }
            )

            continue

        # ----------------------------------------------------
        # Statistics
        # ----------------------------------------------------

        print(
            f"  RANSAC inliers: "
            f"{result['number_inliers']}/"
            f"{result['number_matches']}"
        )

        print(
            f"  Inlier ratio: "
            f"{result['inlier_ratio'] * 100:.1f}%"
        )

        print(
            f"  Mean reprojection error: "
            f"{result['mean_error']:.3f} px"
        )

        print(
            f"  RMS reprojection error: "
            f"{result['rms_error']:.3f} px"
        )

        print(
            f"  Median reprojection error: "
            f"{result['median_error']:.3f} px"
        )

        # ----------------------------------------------------
        # Basic warnings
        # ----------------------------------------------------

        if (
            result[
                "number_inliers"
            ]
            < 10
        ):

            print(
                "  WARNING: very few RANSAC inliers."
            )

        if (
            result[
                "inlier_ratio"
            ]
            < 0.30
        ):

            print(
                "  WARNING: low inlier ratio."
            )

        # ----------------------------------------------------
        # Print H
        # ----------------------------------------------------

        print()

        print(
            "  H (image A -> image B):"
        )

        for row in (
            result[
                "homography_a_to_b"
            ]
        ):

            print(
                "   ",
                row,
            )

        # ----------------------------------------------------
        # Save homography
        # ----------------------------------------------------

        output_file = (
            output_dir
            / (
                f"pair_"
                f"{pair['pair_id']:02d}"
                f"_homography.npz"
            )
        )

        save_homography(
            output_file=(
                output_file
            ),
            pair_data=(
                pair
            ),
            result=(
                result
            ),
            reprojection_threshold=(
                reprojection_threshold
            ),
            confidence=(
                confidence
            ),
            max_iterations=(
                max_iterations
            ),
        )

        print()

        print(
            f"  Saved: "
            f"{output_file}"
        )

        # ----------------------------------------------------
        # Debug visualization
        # ----------------------------------------------------

        image_path_a = find_image(
            image_dir,
            pair[
                "image_a"
            ],
        )

        image_path_b = find_image(
            image_dir,
            pair[
                "image_b"
            ],
        )

        image_a = cv2.imread(
            str(
                image_path_a
            )
        )

        image_b = cv2.imread(
            str(
                image_path_b
            )
        )

        visualization = (
            create_ransac_visualization(
                image_a,
                image_b,
                points_a,
                points_b,
                result[
                    "inlier_mask"
                ],
            )
        )

        debug_file = (
            debug_dir
            / (
                f"pair_"
                f"{pair['pair_id']:02d}"
                f"_ransac.jpg"
            )
        )

        cv2.imwrite(
            str(
                debug_file
            ),
            visualization,
        )

        print(
            f"  Debug: "
            f"{debug_file}"
        )

        print()

        results.append(
            {
                "pair_id": (
                    pair[
                        "pair_id"
                    ]
                ),

                "image_a": (
                    pair[
                        "image_a"
                    ]
                ),

                "image_b": (
                    pair[
                        "image_b"
                    ]
                ),

                "success": True,

                "matches": (
                    result[
                        "number_matches"
                    ]
                ),

                "inliers": (
                    result[
                        "number_inliers"
                    ]
                ),

                "inlier_ratio": (
                    result[
                        "inlier_ratio"
                    ]
                ),

                "rms_error": (
                    result[
                        "rms_error"
                    ]
                ),

                "output_file": str(
                    output_file
                ),
            }
        )

    # ========================================================
    # SAVE SUMMARY
    # ========================================================

    summary_file = (
        output_dir
        / "homography_summary.json"
    )

    with open(
        summary_file,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            {
                "ransac_threshold": (
                    reprojection_threshold
                ),

                "confidence": (
                    confidence
                ),

                "max_iterations": (
                    max_iterations
                ),

                "pairs": (
                    results
                ),
            },
            file,
            indent=4,
        )

    # ========================================================
    # SUMMARY
    # ========================================================

    successful = [
        result

        for result in results

        if result.get(
            "success",
            False,
        )
    ]

    print("========================================")
    print(" HOMOGRAPHY ESTIMATION COMPLETE")
    print("========================================")
    print()

    print(
        f"Pairs processed: "
        f"{len(results)}"
    )

    print(
        f"Successful homographies: "
        f"{len(successful)}/"
        f"{len(results)}"
    )

    if successful:

        average_ratio = np.mean(
            [
                result[
                    "inlier_ratio"
                ]

                for result in successful
            ]
        )

        average_rms = np.mean(
            [
                result[
                    "rms_error"
                ]

                for result in successful
            ]
        )

        print(
            f"Average inlier ratio: "
            f"{average_ratio * 100:.1f}%"
        )

        print(
            f"Average RANSAC RMS error: "
            f"{average_rms:.3f} px"
        )

    print()

    print(
        "Homographies:"
    )

    print(
        output_dir
    )

    print()

    print(
        "RANSAC debug images:"
    )

    print(
        debug_dir
    )

    print()

    print(
        "Summary:"
    )

    print(
        summary_file
    )

    print()

    return results


# ============================================================
# COMMAND LINE
# ============================================================

def parse_arguments():

    parser = argparse.ArgumentParser(
        description=(
            "Estimate planar homographies "
            "between panorama image pairs "
            "using RANSAC."
        )
    )

    parser.add_argument(
        "--matches",
        required=True,
        help=(
            "Directory containing "
            "pair_*_matches.npz files."
        ),
    )

    parser.add_argument(
        "--images",
        required=True,
        help=(
            "Directory containing "
            "undistorted panorama images."
        ),
    )

    parser.add_argument(
        "--output",
        required=True,
        help=(
            "Directory where homography "
            "files will be saved."
        ),
    )

    parser.add_argument(
        "--ransac-threshold",
        type=float,
        default=3.0,
        help=(
            "Maximum reprojection error in pixels "
            "for a match to be considered a "
            "RANSAC inlier. Default: 3.0."
        ),
    )

    parser.add_argument(
        "--confidence",
        type=float,
        default=0.995,
        help=(
            "RANSAC confidence. "
            "Default: 0.995."
        ),
    )

    parser.add_argument(
        "--max-iterations",
        type=int,
        default=5000,
        help=(
            "Maximum RANSAC iterations. "
            "Default: 5000."
        ),
    )

    return parser.parse_args()


# ============================================================
# RUN DIRECTLY
# ============================================================

if __name__ == "__main__":

    args = parse_arguments()

    estimate_all_homographies(
        matches_dir=(
            args.matches
        ),
        image_dir=(
            args.images
        ),
        output_dir=(
            args.output
        ),
        reprojection_threshold=(
            args.ransac_threshold
        ),
        confidence=(
            args.confidence
        ),
        max_iterations=(
            args.max_iterations
        ),
    )