import argparse
import re
from pathlib import Path

import cv2
import numpy as np


# ============================================================
# NATURAL SORTING
# ============================================================

def natural_sort_key(path):
    """
    Natural filename sorting.

    Example:

        1
        2
        10

    instead of:

        1
        10
        2
    """

    return [
        int(text) if text.isdigit()
        else text.lower()

        for text in re.split(
            r"(\d+)",
            path.name,
        )
    ]


# ============================================================
# FIND WARPED IMAGES
# ============================================================

def find_warped_images(
    warped_dir,
):
    """
    Finds warped panorama images generated by warping.py.
    """

    warped_dir = Path(
        warped_dir
    )

    if not warped_dir.exists():

        raise RuntimeError(
            "\nWarped image directory does not exist:\n"
            f"{warped_dir}\n"
        )

    images = list(
        warped_dir.glob(
            "*_warped.png"
        )
    )

    return sorted(
        images,
        key=natural_sort_key,
    )


# ============================================================
# FIND WARPED MASKS
# ============================================================

def find_warped_masks(
    mask_dir,
):
    """
    Finds warped validity masks generated by warping.py.
    """

    mask_dir = Path(
        mask_dir
    )

    if not mask_dir.exists():

        raise RuntimeError(
            "\nWarped mask directory does not exist:\n"
            f"{mask_dir}\n"
        )

    masks = list(
        mask_dir.glob(
            "*_mask.png"
        )
    )

    return sorted(
        masks,
        key=natural_sort_key,
    )


# ============================================================
# LOAD IMAGE + MASK PAIRS
# ============================================================

def load_warped_data(
    warped_dir,
    mask_dir,
):
    """
    Loads every warped image and its corresponding mask.

    All warped images must have the same panorama
    canvas resolution.
    """

    image_paths = (
        find_warped_images(
            warped_dir
        )
    )

    mask_paths = (
        find_warped_masks(
            mask_dir
        )
    )

    if not image_paths:

        raise RuntimeError(
            "No warped images found."
        )

    if len(image_paths) != len(
        mask_paths
    ):

        raise RuntimeError(
            "\nNumber of warped images and masks "
            "does not match.\n"
            f"Images: {len(image_paths)}\n"
            f"Masks:  {len(mask_paths)}\n"
        )

    data = []

    expected_size = None

    for image_path, mask_path in zip(
        image_paths,
        mask_paths,
    ):

        image = cv2.imread(
            str(image_path),
            cv2.IMREAD_COLOR,
        )

        mask = cv2.imread(
            str(mask_path),
            cv2.IMREAD_GRAYSCALE,
        )

        if image is None:

            raise RuntimeError(
                f"Could not read:\n"
                f"{image_path}"
            )

        if mask is None:

            raise RuntimeError(
                f"Could not read:\n"
                f"{mask_path}"
            )

        height, width = (
            image.shape[:2]
        )

        if expected_size is None:

            expected_size = (
                width,
                height,
            )

        elif expected_size != (
            width,
            height,
        ):

            raise RuntimeError(
                "Warped images have "
                "different canvas sizes."
            )

        if mask.shape != (
            height,
            width,
        ):

            raise RuntimeError(
                f"Mask size does not match image:\n"
                f"{mask_path}"
            )

        data.append(
            {
                "image_path": (
                    image_path
                ),

                "mask_path": (
                    mask_path
                ),

                "image": (
                    image
                ),

                "mask": (
                    mask
                ),
            }
        )

    return data


# ============================================================
# CREATE FEATHER WEIGHT MAP
# ============================================================

def create_feather_weights(
    mask,
    feather_power=1.0,
):
    """
    Creates a smooth blending weight from a binary mask.

    Near the image boundary:

        weight -> small

    Toward the center:

        weight -> larger

    When two images overlap, this allows a gradual
    transition instead of a hard seam.
    """

    binary_mask = (
        mask > 0
    ).astype(
        np.uint8
    )

    if np.count_nonzero(
        binary_mask
    ) == 0:

        return np.zeros(
            mask.shape,
            dtype=np.float32,
        )

    # --------------------------------------------------------
    # Distance from each valid pixel to the nearest
    # invalid boundary.
    # --------------------------------------------------------

    distance = cv2.distanceTransform(
        binary_mask,
        cv2.DIST_L2,
        5,
    )

    max_distance = float(
        np.max(
            distance
        )
    )

    if max_distance > 0:

        distance /= (
            max_distance
        )

    # --------------------------------------------------------
    # Optional control over blending curve
    # --------------------------------------------------------

    weights = np.power(
        distance,
        feather_power,
    )

    # --------------------------------------------------------
    # Keep a tiny positive weight even at the valid
    # boundary so no legitimate pixels disappear.
    # --------------------------------------------------------

    weights = np.where(
        binary_mask > 0,
        np.maximum(
            weights,
            1e-3,
        ),
        0.0,
    )

    return weights.astype(
        np.float32
    )


# ============================================================
# FEATHER BLENDING
# ============================================================

def feather_blend(
    warped_data,
    feather_power=1.0,
):
    """
    Combines all warped images using weighted averaging.

    For each panorama pixel:

        panorama =
            sum(image_i * weight_i)
            ---------------------
                 sum(weight_i)
    """

    if not warped_data:

        raise RuntimeError(
            "No warped images supplied."
        )

    first_image = (
        warped_data[0][
            "image"
        ]
    )

    height, width = (
        first_image.shape[:2]
    )

    # --------------------------------------------------------
    # Accumulated weighted color
    # --------------------------------------------------------

    color_accumulator = np.zeros(
        (
            height,
            width,
            3,
        ),
        dtype=np.float32,
    )

    # --------------------------------------------------------
    # Total weight at every pixel
    # --------------------------------------------------------

    weight_accumulator = np.zeros(
        (
            height,
            width,
        ),
        dtype=np.float32,
    )

    coverage_count = np.zeros(
        (
            height,
            width,
        ),
        dtype=np.uint16,
    )

    # ========================================================
    # ACCUMULATE ALL IMAGES
    # ========================================================

    for index, item in enumerate(
        warped_data,
        start=1,
    ):

        image = (
            item[
                "image"
            ].astype(
                np.float32
            )
        )

        mask = (
            item[
                "mask"
            ]
        )

        weights = (
            create_feather_weights(
                mask,
                feather_power=(
                    feather_power
                ),
            )
        )

        print(
            f"[{index}/{len(warped_data)}] "
            f"Adding "
            f"{item['image_path'].name}"
        )

        # ----------------------------------------------------
        # Weighted RGB contribution
        # ----------------------------------------------------

        color_accumulator += (
            image
            * weights[:, :, None]
        )

        weight_accumulator += (
            weights
        )

        coverage_count += (
            mask > 0
        ).astype(
            np.uint16
        )

    # ========================================================
    # NORMALIZE
    # ========================================================

    panorama = np.zeros(
        (
            height,
            width,
            3,
        ),
        dtype=np.float32,
    )

    valid = (
        weight_accumulator > 0
    )

    panorama[
        valid
    ] = (
        color_accumulator[
            valid
        ]
        / weight_accumulator[
            valid,
            None,
        ]
    )

    panorama = np.clip(
        panorama,
        0,
        255,
    ).astype(
        np.uint8
    )

    return (
        panorama,
        valid,
        coverage_count,
    )


# ============================================================
# CROP EMPTY PANORAMA AREA
# ============================================================

def crop_to_content(
    panorama,
    valid_mask,
):
    """
    Removes unused black panorama canvas surrounding
    the final stitched result.
    """

    valid_uint8 = (
        valid_mask.astype(
            np.uint8
        )
        * 255
    )

    points = cv2.findNonZero(
        valid_uint8
    )

    if points is None:

        raise RuntimeError(
            "Panorama contains no valid pixels."
        )

    x, y, width, height = (
        cv2.boundingRect(
            points
        )
    )

    cropped_panorama = (
        panorama[
            y:y + height,
            x:x + width,
        ]
    )

    cropped_mask = (
        valid_uint8[
            y:y + height,
            x:x + width,
        ]
    )

    return (
        cropped_panorama,
        cropped_mask,
        (
            x,
            y,
            width,
            height,
        ),
    )


# ============================================================
# CREATE COVERAGE DEBUG IMAGE
# ============================================================

def create_coverage_visualization(
    coverage_count,
):
    """
    Creates a visualization showing how many warped
    images contribute to each panorama pixel.

    Dark:
        little/no overlap

    Bright:
        more images overlap
    """

    maximum = int(
        np.max(
            coverage_count
        )
    )

    if maximum <= 0:

        return np.zeros(
            coverage_count.shape,
            dtype=np.uint8,
        )

    visualization = (
        coverage_count.astype(
            np.float32
        )
        / maximum
        * 255.0
    )

    return visualization.astype(
        np.uint8
    )


# ============================================================
# MAIN STITCHING FUNCTION
# ============================================================

def stitch_panorama(
    warped_dir,
    mask_dir,
    output_file,
    feather_power=1.0,
):
    """
    Loads warped images, blends overlapping regions,
    removes unused black canvas and saves the final
    panorama.
    """

    warped_dir = Path(
        warped_dir
    )

    mask_dir = Path(
        mask_dir
    )

    output_file = Path(
        output_file
    )

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    debug_dir = (
        output_file.parent
        / "debug"
        / "stitching"
    )

    debug_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print()
    print("========================================")
    print(" PANORAMA STITCHING")
    print("========================================")
    print()

    # ========================================================
    # LOAD WARPED IMAGES
    # ========================================================

    warped_data = (
        load_warped_data(
            warped_dir,
            mask_dir,
        )
    )

    print(
        f"Warped images found: "
        f"{len(warped_data)}"
    )

    print(
        f"Feather power: "
        f"{feather_power}"
    )

    print()

    canvas_height, canvas_width = (
        warped_data[0][
            "image"
        ].shape[:2]
    )

    print(
        "Warped panorama canvas:"
    )

    print(
        f"{canvas_width} x "
        f"{canvas_height}"
    )

    print()

    # ========================================================
    # BLEND
    # ========================================================

    print(
        "Blending warped images..."
    )

    print()

    (
        panorama,
        valid_mask,
        coverage_count,
    ) = feather_blend(
        warped_data,
        feather_power=(
            feather_power
        ),
    )

    # --------------------------------------------------------
    # Save panorama before cropping for debugging
    # --------------------------------------------------------

    uncropped_file = (
        debug_dir
        / "panorama_uncropped.png"
    )

    cv2.imwrite(
        str(
            uncropped_file
        ),
        panorama,
    )

    # ========================================================
    # CROP EMPTY CANVAS
    # ========================================================

    (
        cropped_panorama,
        cropped_mask,
        crop,
    ) = crop_to_content(
        panorama,
        valid_mask,
    )

    (
        crop_x,
        crop_y,
        crop_width,
        crop_height,
    ) = crop

    print()

    print(
        "Final crop:"
    )

    print(
        f"  x = {crop_x}"
    )

    print(
        f"  y = {crop_y}"
    )

    print(
        f"  width  = "
        f"{crop_width}"
    )

    print(
        f"  height = "
        f"{crop_height}"
    )

    # ========================================================
    # SAVE FINAL PANORAMA
    # ========================================================

    success = cv2.imwrite(
        str(
            output_file
        ),
        cropped_panorama,
    )

    if not success:

        raise RuntimeError(
            "\nCould not save final panorama:\n"
            f"{output_file}\n"
        )

    # ========================================================
    # SAVE DEBUG OUTPUTS
    # ========================================================

    mask_file = (
        debug_dir
        / "final_valid_mask.png"
    )

    cv2.imwrite(
        str(
            mask_file
        ),
        cropped_mask,
    )

    coverage = (
        create_coverage_visualization(
            coverage_count
        )
    )

    coverage_file = (
        debug_dir
        / "coverage_map.png"
    )

    cv2.imwrite(
        str(
            coverage_file
        ),
        coverage,
    )

    # ========================================================
    # SUMMARY
    # ========================================================

    final_height, final_width = (
        cropped_panorama.shape[:2]
    )

    maximum_overlap = int(
        np.max(
            coverage_count
        )
    )

    print()
    print("========================================")
    print(" STITCHING COMPLETE")
    print("========================================")
    print()

    print(
        f"Images stitched: "
        f"{len(warped_data)}"
    )

    print()

    print(
        "Final panorama resolution:"
    )

    print(
        f"{final_width} x "
        f"{final_height}"
    )

    print()

    print(
        f"Maximum image overlap: "
        f"{maximum_overlap}"
    )

    print()

    print(
        "Final panorama:"
    )

    print(
        output_file
    )

    print()

    print(
        "Debug outputs:"
    )

    print(
        debug_dir
    )

    print()

    return cropped_panorama


# ============================================================
# COMMAND LINE
# ============================================================

def parse_arguments():

    parser = argparse.ArgumentParser(
        description=(
            "Blend warped panorama images "
            "into one final panorama."
        )
    )

    parser.add_argument(
        "--warped",
        required=True,
        help=(
            "Directory containing "
            "*_warped.png images."
        ),
    )

    parser.add_argument(
        "--masks",
        required=True,
        help=(
            "Directory containing "
            "*_mask.png files."
        ),
    )

    parser.add_argument(
        "--output",
        required=True,
        help=(
            "Path for the final panorama image."
        ),
    )

    parser.add_argument(
        "--feather-power",
        type=float,
        default=1.0,
        help=(
            "Controls feather blending strength. "
            "Default: 1.0."
        ),
    )

    return parser.parse_args()


# ============================================================
# RUN DIRECTLY
# ============================================================

if __name__ == "__main__":

    args = parse_arguments()

    stitch_panorama(
        warped_dir=(
            args.warped
        ),
        mask_dir=(
            args.masks
        ),
        output_file=(
            args.output
        ),
        feather_power=(
            args.feather_power
        ),
    )