import argparse
import json
import re
from pathlib import Path

import cv2
import numpy as np

from homography import load_homography


# ============================================================
# NATURAL SORTING
# ============================================================

def natural_sort_key(path):
    """
    Natural filename sorting.

    Example:

        image1
        image2
        image10
    """

    return [
        int(text) if text.isdigit()
        else text.lower()

        for text in re.split(
            r"(\d+)",
            path.name,
        )
    ]


# ============================================================
# FIND HOMOGRAPHY FILES
# ============================================================

def find_homography_files(
    homography_dir,
):
    """
    Finds pairwise homographies generated by homography.py.
    """

    homography_dir = Path(
        homography_dir
    )

    if not homography_dir.exists():

        raise RuntimeError(
            "\nHomography directory does not exist:\n"
            f"{homography_dir}\n"
        )

    files = list(
        homography_dir.glob(
            "pair_*_homography.npz"
        )
    )

    return sorted(
        files,
        key=natural_sort_key,
    )


# ============================================================
# LOAD HOMOGRAPHY CHAIN
# ============================================================

def load_homography_chain(
    homography_dir,
):
    """
    Loads all adjacent-image homographies.

    Expected sequence:

        image0 -> image1
        image1 -> image2
        image2 -> image3
        ...
    """

    files = find_homography_files(
        homography_dir
    )

    if not files:

        raise RuntimeError(
            "\nNo homography files found in:\n"
            f"{homography_dir}\n"
        )

    homographies = []

    for file in files:

        data = load_homography(
            file
        )

        homographies.append(
            data
        )

    # --------------------------------------------------------
    # Verify pair chain
    # --------------------------------------------------------

    for index in range(
        len(homographies) - 1
    ):

        current = (
            homographies[index]
        )

        following = (
            homographies[
                index + 1
            ]
        )

        if (
            current["image_b"]
            != following["image_a"]
        ):

            raise RuntimeError(
                "\nHomography chain is broken.\n\n"
                f"Pair {index} ends with:\n"
                f"  {current['image_b']}\n\n"
                f"Next pair starts with:\n"
                f"  {following['image_a']}\n"
            )

    return homographies


# ============================================================
# GET IMAGE SEQUENCE
# ============================================================

def build_image_sequence(
    homographies,
):
    """
    Reconstructs the panorama image order directly
    from the homography chain.

    Example:

        pair 0: image01 -> image02
        pair 1: image02 -> image03

    produces:

        image01
        image02
        image03
    """

    if not homographies:

        return []

    image_names = [
        homographies[0][
            "image_a"
        ]
    ]

    for homography in homographies:

        image_names.append(
            homography[
                "image_b"
            ]
        )

    return image_names


# ============================================================
# LOAD IMAGES
# ============================================================

def load_images(
    image_dir,
    image_names,
):
    """
    Loads the undistorted panorama images in
    exactly the same order as the homography chain.
    """

    image_dir = Path(
        image_dir
    )

    images = []

    for image_name in image_names:

        image_path = (
            image_dir
            / image_name
        )

        if not image_path.exists():

            raise RuntimeError(
                "\nPanorama image not found:\n"
                f"{image_path}\n"
            )

        image = cv2.imread(
            str(image_path)
        )

        if image is None:

            raise RuntimeError(
                "\nCould not read image:\n"
                f"{image_path}\n"
            )

        images.append(
            {
                "name": image_name,
                "path": image_path,
                "image": image,
            }
        )

    return images


# ============================================================
# COMPOSE GLOBAL TRANSFORMATIONS
# ============================================================

def compose_global_transforms(
    homographies,
    number_images,
    reference_index,
):
    """
    Creates one transformation for every image.

    Each transformation maps:

        IMAGE i
            ↓
        REFERENCE IMAGE coordinates


    Example with image 3 as reference:

        image1 -> image2 -> image3
        image2 -> image3
        image3 -> identity
        image4 -> image3
        image5 -> image4 -> image3
    """

    if (
        reference_index < 0
        or reference_index >= number_images
    ):

        raise ValueError(
            "Invalid reference image index."
        )

    transforms = [
        None
        for _ in range(
            number_images
        )
    ]

    # --------------------------------------------------------
    # Reference image
    # --------------------------------------------------------

    transforms[
        reference_index
    ] = np.eye(
        3,
        dtype=np.float64,
    )

    # ========================================================
    # LEFT SIDE OF REFERENCE
    # ========================================================
    #
    # Pair homography:
    #
    #     H_i:
    #     image i -> image i+1
    #
    # Therefore:
    #
    #     T_i =
    #         T_(i+1) @ H_i
    #

    for image_index in range(
        reference_index - 1,
        -1,
        -1,
    ):

        pair = (
            homographies[
                image_index
            ]
        )

        H_i_to_next = (
            pair[
                "homography_a_to_b"
            ]
        )

        transforms[
            image_index
        ] = (
            transforms[
                image_index + 1
            ]
            @ H_i_to_next
        )

        transforms[
            image_index
        ] /= (
            transforms[
                image_index
            ][2, 2]
        )

    # ========================================================
    # RIGHT SIDE OF REFERENCE
    # ========================================================
    #
    # To move image i toward the reference,
    # we need:
    #
    #     image i -> image i-1
    #
    # which is H_b_to_a from pair i-1.
    #

    for image_index in range(
        reference_index + 1,
        number_images,
    ):

        pair = (
            homographies[
                image_index - 1
            ]
        )

        H_i_to_previous = (
            pair[
                "homography_b_to_a"
            ]
        )

        transforms[
            image_index
        ] = (
            transforms[
                image_index - 1
            ]
            @ H_i_to_previous
        )

        transforms[
            image_index
        ] /= (
            transforms[
                image_index
            ][2, 2]
        )

    return transforms


# ============================================================
# IMAGE CORNERS
# ============================================================

def image_corners(
    image,
):
    """
    Returns the four image corners:

        top-left
        top-right
        bottom-right
        bottom-left
    """

    height, width = (
        image.shape[:2]
    )

    return np.array(
        [
            [
                0.0,
                0.0,
            ],
            [
                float(
                    width - 1
                ),
                0.0,
            ],
            [
                float(
                    width - 1
                ),
                float(
                    height - 1
                ),
            ],
            [
                0.0,
                float(
                    height - 1
                ),
            ],
        ],
        dtype=np.float32,
    )


# ============================================================
# TRANSFORM CORNERS
# ============================================================

def transform_corners(
    image,
    transform,
):
    """
    Transforms the four corners of an image
    into the panorama reference coordinate system.
    """

    corners = image_corners(
        image
    )

    corners = corners.reshape(
        -1,
        1,
        2,
    )

    transformed = (
        cv2.perspectiveTransform(
            corners,
            transform,
        )
    )

    return transformed.reshape(
        -1,
        2,
    )


# ============================================================
# CALCULATE PANORAMA CANVAS
# ============================================================

def calculate_canvas(
    images,
    transforms,
):
    """
    Determines how large the panorama canvas must be
    to contain all transformed images.
    """

    all_corners = []

    transformed_corners = []

    for image_data, transform in zip(
        images,
        transforms,
    ):

        corners = transform_corners(
            image_data[
                "image"
            ],
            transform,
        )

        transformed_corners.append(
            corners
        )

        all_corners.append(
            corners
        )

    all_corners = np.vstack(
        all_corners
    )

    if not np.all(
        np.isfinite(
            all_corners
        )
    ):

        raise RuntimeError(
            "Invalid transformed image coordinates."
        )

    min_x = float(
        np.floor(
            np.min(
                all_corners[:, 0]
            )
        )
    )

    min_y = float(
        np.floor(
            np.min(
                all_corners[:, 1]
            )
        )
    )

    max_x = float(
        np.ceil(
            np.max(
                all_corners[:, 0]
            )
        )
    )

    max_y = float(
        np.ceil(
            np.max(
                all_corners[:, 1]
            )
        )
    )

    canvas_width = int(
        max_x
        - min_x
        + 1
    )

    canvas_height = int(
        max_y
        - min_y
        + 1
    )

    # --------------------------------------------------------
    # Safety checks
    # --------------------------------------------------------

    if (
        canvas_width <= 0
        or canvas_height <= 0
    ):

        raise RuntimeError(
            "Invalid panorama canvas size."
        )

    # Something is probably wrong if the homographies
    # explode the panorama to a ridiculous size.

    if (
        canvas_width > 30000
        or canvas_height > 30000
    ):

        raise RuntimeError(
            "\nPanorama canvas became extremely large:\n"
            f"{canvas_width} x {canvas_height}\n\n"
            "This usually means one of the homographies "
            "is unstable."
        )

    # --------------------------------------------------------
    # Translation matrix
    #
    # Some transformed images may have negative x/y.
    # Move everything so the canvas starts at (0, 0).
    # --------------------------------------------------------

    translation = np.array(
        [
            [
                1.0,
                0.0,
                -min_x,
            ],
            [
                0.0,
                1.0,
                -min_y,
            ],
            [
                0.0,
                0.0,
                1.0,
            ],
        ],
        dtype=np.float64,
    )

    return {
        "width": (
            canvas_width
        ),

        "height": (
            canvas_height
        ),

        "min_x": (
            min_x
        ),

        "min_y": (
            min_y
        ),

        "max_x": (
            max_x
        ),

        "max_y": (
            max_y
        ),

        "translation": (
            translation
        ),

        "corners": (
            transformed_corners
        ),
    }


# ============================================================
# WARP ONE IMAGE
# ============================================================

def warp_image(
    image,
    transform,
    translation,
    canvas_size,
):
    """
    Warps one image into panorama coordinates using
    cv2.warpPerspective().

    Also warps a binary mask showing which pixels
    belong to the image.
    """

    canvas_width, canvas_height = (
        canvas_size
    )

    final_transform = (
        translation
        @ transform
    )

    # --------------------------------------------------------
    # Warp image
    # --------------------------------------------------------

    warped = cv2.warpPerspective(
        image,
        final_transform,
        (
            canvas_width,
            canvas_height,
        ),
        flags=cv2.INTER_LINEAR,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=(
            0,
            0,
            0,
        ),
    )

    # --------------------------------------------------------
    # Original image validity mask
    # --------------------------------------------------------

    original_mask = np.full(
        image.shape[:2],
        255,
        dtype=np.uint8,
    )

    warped_mask = cv2.warpPerspective(
        original_mask,
        final_transform,
        (
            canvas_width,
            canvas_height,
        ),
        flags=cv2.INTER_NEAREST,
        borderMode=cv2.BORDER_CONSTANT,
        borderValue=0,
    )

    return (
        warped,
        warped_mask,
        final_transform,
    )


# ============================================================
# SAVE GLOBAL TRANSFORMS
# ============================================================

def save_global_transforms(
    output_file,
    image_names,
    transforms,
    canvas,
    reference_index,
):
    """
    Saves global panorama geometry for later stages.
    """

    output_file = Path(
        output_file
    )

    np.savez_compressed(
        output_file,

        image_names=np.asarray(
            image_names
        ),

        transforms=np.asarray(
            transforms
        ),

        translation=(
            canvas[
                "translation"
            ]
        ),

        canvas_width=np.array(
            canvas[
                "width"
            ]
        ),

        canvas_height=np.array(
            canvas[
                "height"
            ]
        ),

        reference_index=np.array(
            reference_index
        ),
    )


# ============================================================
# MAIN WARPING PIPELINE
# ============================================================

def warp_panorama_images(
    homography_dir,
    image_dir,
    output_dir,
    reference_index=None,
):
    """
    Takes pairwise homographies and places all images
    into one panorama coordinate system.
    """

    homography_dir = Path(
        homography_dir
    )

    image_dir = Path(
        image_dir
    )

    output_dir = Path(
        output_dir
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    mask_dir = (
        output_dir.parent
        / "warped_masks"
    )

    mask_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ========================================================
    # LOAD HOMOGRAPHIES
    # ========================================================

    homographies = (
        load_homography_chain(
            homography_dir
        )
    )

    image_names = (
        build_image_sequence(
            homographies
        )
    )

    number_images = len(
        image_names
    )

    # n images require n-1 pairwise homographies.
    if (
        len(homographies)
        != number_images - 1
    ):

        raise RuntimeError(
            "Invalid homography/image chain."
        )

    # ========================================================
    # LOAD IMAGES
    # ========================================================

    images = load_images(
        image_dir,
        image_names,
    )

    # ========================================================
    # REFERENCE IMAGE
    # ========================================================

    if reference_index is None:

        reference_index = (
            number_images // 2
        )

    if (
        reference_index < 0
        or reference_index >= number_images
    ):

        raise RuntimeError(
            f"Reference index must be between "
            f"0 and {number_images - 1}."
        )

    print()
    print("========================================")
    print(" PANORAMA PERSPECTIVE WARPING")
    print("========================================")
    print()

    print(
        f"Images: "
        f"{number_images}"
    )

    print(
        f"Pairwise homographies: "
        f"{len(homographies)}"
    )

    print()

    print(
        "Reference image:"
    )

    print(
        f"  index = "
        f"{reference_index}"
    )

    print(
        f"  image = "
        f"{image_names[reference_index]}"
    )

    print()

    # ========================================================
    # GLOBAL TRANSFORMS
    # ========================================================

    transforms = (
        compose_global_transforms(
            homographies=(
                homographies
            ),
            number_images=(
                number_images
            ),
            reference_index=(
                reference_index
            ),
        )
    )

    print(
        "Global transforms calculated."
    )

    print()

    for index, transform in enumerate(
        transforms
    ):

        print(
            f"Image {index:02d}: "
            f"{image_names[index]}"
        )

        print(
            transform
        )

        print()

    # ========================================================
    # CALCULATE CANVAS
    # ========================================================

    canvas = calculate_canvas(
        images,
        transforms,
    )

    print(
        "Panorama canvas:"
    )

    print(
        f"  width  = "
        f"{canvas['width']} px"
    )

    print(
        f"  height = "
        f"{canvas['height']} px"
    )

    print()

    print(
        "Original transformed bounds:"
    )

    print(
        f"  x: "
        f"{canvas['min_x']:.1f}"
        f" -> "
        f"{canvas['max_x']:.1f}"
    )

    print(
        f"  y: "
        f"{canvas['min_y']:.1f}"
        f" -> "
        f"{canvas['max_y']:.1f}"
    )

    print()

    # ========================================================
    # WARP EVERY IMAGE
    # ========================================================

    results = []

    canvas_size = (
        canvas[
            "width"
        ],
        canvas[
            "height"
        ],
    )

    for index, (
        image_data,
        transform,
    ) in enumerate(
        zip(
            images,
            transforms,
        ),
        start=0,
    ):

        print(
            f"[{index + 1}/{number_images}] "
            f"Warping "
            f"{image_data['name']}"
        )

        (
            warped,
            warped_mask,
            final_transform,
        ) = warp_image(
            image=(
                image_data[
                    "image"
                ]
            ),
            transform=(
                transform
            ),
            translation=(
                canvas[
                    "translation"
                ]
            ),
            canvas_size=(
                canvas_size
            ),
        )

        # ----------------------------------------------------
        # Save as PNG so repeated processing does not
        # introduce JPEG compression.
        # ----------------------------------------------------

        image_stem = Path(
            image_data[
                "name"
            ]
        ).stem

        warped_path = (
            output_dir
            / (
                f"{index:02d}_"
                f"{image_stem}"
                f"_warped.png"
            )
        )

        mask_path = (
            mask_dir
            / (
                f"{index:02d}_"
                f"{image_stem}"
                f"_mask.png"
            )
        )

        cv2.imwrite(
            str(
                warped_path
            ),
            warped,
        )

        cv2.imwrite(
            str(
                mask_path
            ),
            warped_mask,
        )

        print(
            f"  Image: "
            f"{warped_path}"
        )

        print(
            f"  Mask: "
            f"{mask_path}"
        )

        print()

        results.append(
            {
                "index": (
                    index
                ),

                "image_name": (
                    image_data[
                        "name"
                    ]
                ),

                "warped_image": (
                    str(
                        warped_path
                    )
                ),

                "mask": (
                    str(
                        mask_path
                    )
                ),

                "transform": (
                    final_transform
                ),
            }
        )

    # ========================================================
    # SAVE GLOBAL GEOMETRY
    # ========================================================

    geometry_file = (
        output_dir.parent
        / "panorama_geometry.npz"
    )

    save_global_transforms(
        output_file=(
            geometry_file
        ),
        image_names=(
            image_names
        ),
        transforms=(
            transforms
        ),
        canvas=(
            canvas
        ),
        reference_index=(
            reference_index
        ),
    )

    # ========================================================
    # SAVE JSON SUMMARY
    # ========================================================

    summary_file = (
        output_dir.parent
        / "warping_summary.json"
    )

    summary = {
        "number_images": (
            number_images
        ),

        "reference_index": (
            reference_index
        ),

        "reference_image": (
            image_names[
                reference_index
            ]
        ),

        "canvas_width": (
            canvas[
                "width"
            ]
        ),

        "canvas_height": (
            canvas[
                "height"
            ]
        ),

        "images": [
            {
                "index": (
                    result[
                        "index"
                    ]
                ),

                "image_name": (
                    result[
                        "image_name"
                    ]
                ),

                "warped_image": (
                    result[
                        "warped_image"
                    ]
                ),

                "mask": (
                    result[
                        "mask"
                    ]
                ),
            }

            for result in results
        ],
    }

    with open(
        summary_file,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            summary,
            file,
            indent=4,
        )

    # ========================================================
    # FINAL SUMMARY
    # ========================================================

    print("========================================")
    print(" WARPING COMPLETE")
    print("========================================")
    print()

    print(
        f"Warped images: "
        f"{len(results)}/"
        f"{number_images}"
    )

    print()

    print(
        "Reference image:"
    )

    print(
        image_names[
            reference_index
        ]
    )

    print()

    print(
        "Panorama canvas:"
    )

    print(
        f"{canvas['width']} x "
        f"{canvas['height']}"
    )

    print()

    print(
        "Warped images:"
    )

    print(
        output_dir
    )

    print()

    print(
        "Warped masks:"
    )

    print(
        mask_dir
    )

    print()

    print(
        "Geometry:"
    )

    print(
        geometry_file
    )

    print()

    print(
        "Summary:"
    )

    print(
        summary_file
    )

    print()

    return results


# ============================================================
# COMMAND LINE
# ============================================================

def parse_arguments():

    parser = argparse.ArgumentParser(
        description=(
            "Warp panorama images into a common "
            "coordinate system using pairwise "
            "homographies."
        )
    )

    parser.add_argument(
        "--homographies",
        required=True,
        help=(
            "Directory containing pairwise "
            "homography NPZ files."
        ),
    )

    parser.add_argument(
        "--images",
        required=True,
        help=(
            "Directory containing the "
            "undistorted panorama images."
        ),
    )

    parser.add_argument(
        "--output",
        required=True,
        help=(
            "Directory where warped images "
            "will be saved."
        ),
    )

    parser.add_argument(
        "--reference-index",
        type=int,
        default=None,
        help=(
            "Reference image index, starting at 0. "
            "If omitted, the middle image is used."
        ),
    )

    return parser.parse_args()


# ============================================================
# RUN DIRECTLY
# ============================================================

if __name__ == "__main__":

    args = parse_arguments()

    warp_panorama_images(
        homography_dir=(
            args.homographies
        ),
        image_dir=(
            args.images
        ),
        output_dir=(
            args.output
        ),
        reference_index=(
            args.reference_index
        ),
    )